### ISSUE TITLE
Something can be improved

### ISSUE THREAD

**Issue by LIYINGZHEN** [codefun-io/dribbble-love-travel#1]
- [x] Try increasing the margin-top of the page. It's bigger on the initial design. You can see how the border of the "Create Account" button seems to close to the top of the page.

- [x] You are not using Bootstrap yet, but you should always try to use some kind of grid system. Are you familiar with Bootstrap's grid or grids in general? Take a look at the following image: https://www.dropbox.com/s/i2x12wsrundsywf/grid.png?dl=0, do you see how the three blocks of text seem to be aligned with three columns of equal width? In your implementation, the text in your third column is not reaching the line where the Search form finishes.

- [x] The font size of "See all ->" seems a little bit too small

- [x] The margin between the boxes seems smaller than in the design

- [x] The shadow around the boxes seem to have a lower opacity or lighter color in the design

- [x] The color of the main text in the boxes seems to dark compared to the design

- [x] The image used for the map looks a little bit pixeled

- [x] In the mobile version, the margin at the bottom of each box should be bigger (they are too close to each other right now)

**Comment by polo13999** [comment]
it's done
